name: Trigger auto deployment for movie-backend-testing

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/movie-backend-testing-AutoDeployTrigger-d7001e81-392e-4ebf-8185-cef0c161f64a.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MOVIEBACKENDTESTING_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: js
          registryUsername: ${{ secrets.MOVIEBACKENDTESTING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MOVIEBACKENDTESTING_REGISTRY_PASSWORD }}
          containerAppName: movie-backend-testing
          resourceGroup: SSE-movies
          imageToBuild: js/movie-backend-testing:${{ github.sha }}
          
            

     

